"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useMyTeam } from "@/lib/user-cards/hooks";
import { useLocale, useT } from "@/lib/i18n/LocaleContext";
import { resolvePlayerDisplayName } from "@/lib/i18n/display-name";
import { listBuilds } from "@/lib/progression/build-storage";
import type { SavedBuild } from "@/lib/progression/types";
import { getFormation } from "@/lib/squad/formations";
import { useBestXiProgressionCards } from "@/lib/best-xi/use-candidate-cards";
import { buildBestXiCandidates } from "@/lib/best-xi/candidates";
import { selectBestXi } from "@/lib/best-xi/select";
import {
  EXCLUSION_REASON_LABEL_KEY,
  LIMITATION_LABEL_KEY,
  SELECTION_REASON_LABEL_KEY,
  UNAVAILABLE_CARD_LABEL_KEY,
  UNFILLED_SLOT_REASON_LABEL_KEY,
} from "@/lib/best-xi/reason-labels";
import type {
  BestXiCandidate,
  BestXiSelectedSlot,
  BestXiSelectionResult,
  BestXiUnfilledSlot,
} from "@/lib/best-xi/types";
import { PageHeader } from "@/components/ui/PageHeader";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Icon } from "@/components/ui/Icon";
import type { Dictionary } from "@/lib/i18n/dictionaries/ja";

const FORMATION_ID = "4-3-3";

function fillTemplate(s: string, vars: Record<string, string>): string {
  return Object.entries(vars).reduce((acc, [k, v]) => acc.replace(`{${k}}`, v), s);
}

function candidateSignature(candidates: BestXiCandidate[]): string {
  return candidates
    .map((c) => `${c.candidateKey}:${c.abilityStatus}:${c.buildName ?? ""}:${c.ruleKind}`)
    .sort()
    .join("|");
}

export function BestXiView() {
  const t = useT();
  const { locale } = useLocale();
  const tb = useCallback((key: string) => t("bestXi", key as keyof Dictionary["bestXi"]), [t]);
  const fillTb = useCallback((key: string, vars: Record<string, string>) => fillTemplate(tb(key), vars), [tb]);

  const { myTeam, available: myTeamAvailable } = useMyTeam();
  const ownedWorldCardIds = useMemo(
    () => [...new Set(myTeam.filter((r) => r.ownershipStatus === "owned").map((r) => r.worldCardId))],
    [myTeam],
  );
  const { cards: progressionCards, loading: cardsLoading } = useBestXiProgressionCards(ownedWorldCardIds);

  // 保存ビルドはクライアントのlocalStorageから読む(build-storageに変更通知イベントが無いため、
  // マウント時と「再選出」操作のタイミングで読み直す)。
  const [buildsByWorldCardId, setBuildsByWorldCardId] = useState<Map<string, SavedBuild[]>>(new Map());
  const reloadBuilds = useCallback(() => {
    const map = new Map<string, SavedBuild[]>();
    for (const id of ownedWorldCardIds) map.set(id, listBuilds(id));
    setBuildsByWorldCardId(map);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ownedWorldCardIds.join(",")]);
  useEffect(() => {
    reloadBuilds();
  }, [reloadBuilds]);

  const { candidates, unavailableCards } = useMemo(
    () => buildBestXiCandidates({ myTeam, progressionCards, buildsByWorldCardId }),
    [myTeam, progressionCards, buildsByWorldCardId],
  );

  const poolPlayerCount = useMemo(
    () => new Set(candidates.filter((c) => c.abilityStatus === "available").map((c) => c.worldCardId)).size,
    [candidates],
  );
  const poolBuildCount = useMemo(
    () => candidates.filter((c) => c.source === "build" && c.abilityStatus === "available").length,
    [candidates],
  );

  const [result, setResult] = useState<BestXiSelectionResult | null>(null);
  const [resultSignature, setResultSignature] = useState<string | null>(null);
  // 初回の1回だけは自動生成し(section 23で許可)、以降はユーザーの明示操作(再選出ボタン)でのみ
  // 選考を実行する。ボタン押下時はまず保存ビルドを読み直し(reloadBuilds)、その結果candidatesが
  // 更新されたタイミングで実際の選考を実行する(pendingGenerateRefで「押下直後の1回だけ」に絞る)。
  const autoGeneratedRef = useRef(false);
  const pendingGenerateRef = useRef(false);

  const runSelection = useCallback(() => {
    const r = selectBestXi({ formationId: FORMATION_ID, candidates, unavailableCards, generatedAt: new Date().toISOString() });
    setResult(r);
    setResultSignature(candidateSignature(candidates));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [candidates, unavailableCards]);

  useEffect(() => {
    if (cardsLoading) return;
    if (candidates.length === 0 && unavailableCards.length === 0) return;
    if (autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    runSelection();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cardsLoading, candidates, unavailableCards]);

  useEffect(() => {
    if (!pendingGenerateRef.current) return;
    if (cardsLoading) return;
    pendingGenerateRef.current = false;
    runSelection();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [candidates, unavailableCards, cardsLoading]);

  const handleGenerateButton = useCallback(() => {
    pendingGenerateRef.current = true;
    reloadBuilds();
  }, [reloadBuilds]);

  const currentSignature = useMemo(() => candidateSignature(candidates), [candidates]);
  const isStale = result != null && resultSignature != null && currentSignature !== resultSignature;

  const formation = getFormation(FORMATION_ID);
  const slotsById = new Map(formation.slots.map((s) => [s.slotId, s]));
  const selectedBySlotId = new Map((result?.slots ?? []).map((s) => [s.slotId, s]));
  const unfilledBySlotId = new Map((result?.unfilledSlots ?? []).map((s) => [s.slotId, s]));

  const displayName = useCallback(
    (c: BestXiCandidate) => resolvePlayerDisplayName({ nameJa: c.nameJa, nameEn: c.nameEn }, locale, null),
    [locale],
  );

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        title={tb("heading")}
        icon="trophy"
        description={tb("description")}
        meta={<Badge tone="accent">{tb("modeLabel")}</Badge>}
      />

      <div className="rounded-card border border-border bg-surface p-3 text-xs text-text-dim sm:p-4">
        <p>{tb("disclaimerNotAi")}</p>
        <p className="mt-1">{tb("modeDescription")}</p>
        <p className="mt-1 font-semibold text-text">{tb("formationNotice")}</p>
        <p className="mt-1">{tb("withinYourCandidatesText")}</p>
        <p className="mt-1">{tb("notAWinPredictionText")}</p>
        <p className="mt-1">{tb("resultsNotSavedText")}</p>
        <details className="mt-2">
          <summary className="cursor-pointer font-semibold text-text-dim">{tb("criteriaHeading")}</summary>
          <ol className="mt-1 list-decimal pl-4">
            <li>{tb("criteriaFilledSlots").replace(/^\d+\.\s*/, "")}</li>
            <li>{tb("criteriaExactPosition").replace(/^\d+\.\s*/, "")}</li>
            <li>{tb("criteriaRelatedMinimized").replace(/^\d+\.\s*/, "")}</li>
            <li>{tb("criteriaPositionRatingBalance").replace(/^\d+\.\s*/, "")}</li>
            <li>{tb("criteriaAbilityDataConfidence").replace(/^\d+\.\s*/, "")}</li>
            <li>{tb("criteriaIntentSupplementary").replace(/^\d+\.\s*/, "")}</li>
          </ol>
        </details>
      </div>

      {!myTeamAvailable ? null : ownedWorldCardIds.length === 0 ? (
        <div role="status" className="rounded-card border border-border bg-surface p-4 text-sm">
          <p className="font-semibold text-text">{tb("emptyMyTeamHeading")}</p>
          <p className="mt-1 text-text-dim">{tb("emptyMyTeamBody")}</p>
          <div className="mt-3 flex flex-wrap gap-2">
            <Link href="/my-team" className="inline-flex min-h-[36px] items-center rounded-md border border-accent bg-accent-soft px-3 text-xs font-semibold text-accent">
              {tb("goToMyTeamLink")}
            </Link>
            <Link href="/build-inventory" className="inline-flex min-h-[36px] items-center rounded-md border border-border px-3 text-xs">
              {tb("goToBuildInventoryLink")}
            </Link>
          </div>
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-card border border-border bg-surface p-3 text-xs sm:p-4">
            <p aria-live="polite" className="text-text-dim">
              {fillTb("candidatePoolTemplate", { playerCount: String(poolPlayerCount), buildCount: String(poolBuildCount) })}
            </p>
            <div className="flex items-center gap-2">
              {cardsLoading ? (
                <span role="status" aria-live="polite" className="text-2xs text-text-muted">
                  {tb("generatingText")}
                </span>
              ) : null}
              <Button variant="primary" size="sm" iconLeft="sparkles" onClick={handleGenerateButton} disabled={cardsLoading}>
                {result ? tb("regenerateButton") : tb("generateButton")}
              </Button>
            </div>
          </div>

          {isStale ? (
            <p role="status" className="rounded border border-warning/40 bg-warning/10 px-3 py-2 text-xs text-warning">
              {tb("staleNoticeText")}
            </p>
          ) : null}

          {unavailableCards.length > 0 ? (
            <details className="rounded-card border border-border bg-surface p-3 text-xs sm:p-4">
              <summary className="cursor-pointer font-semibold text-text-dim">
                {tb("unavailableCardsHeading")} ({unavailableCards.length})
              </summary>
              <ul className="mt-2 flex flex-col gap-1">
                {unavailableCards.map((u) => (
                  <li key={u.worldCardId} className="text-text-dim">
                    {t("bestXi", UNAVAILABLE_CARD_LABEL_KEY[u.reason] as keyof Dictionary["bestXi"])}
                  </li>
                ))}
              </ul>
            </details>
          ) : null}

          {result ? (
            <>
              <p aria-live="polite" className="rounded-card border border-border bg-surface p-3 text-xs font-semibold text-text sm:p-4">
                {fillTb("resultStatsTemplate", {
                  filled: String(result.filledRequiredSlotCount),
                  exact: String(result.exactSelectionCount),
                  related: String(result.relatedSelectionCount),
                })}
              </p>

              <BestXiPitch
                slots={formation.slots}
                selectedBySlotId={selectedBySlotId}
                unfilledBySlotId={unfilledBySlotId}
                displayName={displayName}
                tb={tb}
              />

              <BestXiSlotList
                slots={formation.slots}
                selectedBySlotId={selectedBySlotId}
                unfilledBySlotId={unfilledBySlotId}
                displayName={displayName}
                tb={tb}
                fillTb={fillTb}
                t={t}
              />

              {result.unfilledSlots.length > 0 ? (
                <div className="rounded-card border border-warning/40 bg-warning/10 p-3 text-xs sm:p-4">
                  <p className="font-semibold text-warning">{tb("unfilledSlotsHeading")}</p>
                  <ul className="mt-2 flex flex-col gap-1">
                    {result.unfilledSlots.map((u) => (
                      <li key={u.slotId}>
                        <span className="font-semibold">{u.position}</span>: {t("bestXi", UNFILLED_SLOT_REASON_LABEL_KEY[u.reason] as keyof Dictionary["bestXi"])}
                      </li>
                    ))}
                  </ul>
                  <p className="mt-2">
                    {result.unfilledSlots.length === 1
                      ? tb("needOnePlayerText")
                      : fillTb("needMorePlayersTemplate", { count: String(result.unfilledSlots.length) })}
                  </p>
                  <p className="mt-1 text-text-dim">{tb("addPlayersHint")}</p>
                </div>
              ) : null}

              <BestXiExclusions result={result} displayName={displayName} tb={tb} fillTb={fillTb} t={t} />

              <div className="rounded-card border border-border bg-surface p-3 text-2xs text-text-muted sm:p-4">
                <p className="font-semibold text-text-dim">{tb("limitationsHeading")}</p>
                <ul className="mt-1 list-disc pl-4">
                  {result.limitationCodes.map((code) => (
                    <li key={code}>{t("bestXi", LIMITATION_LABEL_KEY[code] as keyof Dictionary["bestXi"])}</li>
                  ))}
                </ul>
              </div>
            </>
          ) : null}
        </>
      )}
    </div>
  );
}

function suitabilityLabelKey(tier: "exact" | "related" | "unresolved" | "excluded"): keyof Dictionary["bestXi"] {
  if (tier === "exact") return "suitabilityExact";
  if (tier === "related") return "suitabilityRelated";
  return "suitabilityUnresolved";
}

function BestXiPitch({
  slots,
  selectedBySlotId,
  unfilledBySlotId,
  displayName,
  tb,
}: {
  slots: { slotId: string; position: string; x: number; y: number }[];
  selectedBySlotId: Map<string, BestXiSelectedSlot>;
  unfilledBySlotId: Map<string, BestXiUnfilledSlot>;
  displayName: (c: BestXiCandidate) => string;
  tb: (key: string) => string;
}) {
  return (
    <div className="rounded-card border border-border bg-surface p-3 sm:p-4">
      <p className="mb-2 text-xs font-semibold text-text-dim">{tb("pitchViewHeading")}</p>
      <div className="relative mx-auto aspect-[68/105] w-full max-w-sm rounded-md border border-border bg-surface-2/40">
        {slots.map((slot) => {
          const sel = selectedBySlotId.get(slot.slotId);
          const unfilled = unfilledBySlotId.get(slot.slotId);
          return (
            <div
              key={slot.slotId}
              className="absolute flex w-[30%] -translate-x-1/2 -translate-y-1/2 flex-col items-center text-center"
              style={{ left: `${slot.x}%`, top: `${slot.y}%` }}
            >
              <span
                className={`inline-flex min-h-[28px] w-full items-center justify-center rounded-md border px-1 text-2xs font-semibold ${
                  sel
                    ? sel.suitability.tier === "exact"
                      ? "border-accent bg-accent-soft text-accent"
                      : "border-info/60 bg-info/10 text-info"
                    : unfilled
                      ? "border-warning/50 bg-warning/10 text-warning"
                      : "border-border bg-surface text-text-muted"
                }`}
                title={sel ? displayName(sel.candidate) : undefined}
              >
                {sel ? truncateName(displayName(sel.candidate)) : tb("slotEmptyLabel")}
              </span>
              <span className="mt-0.5 text-2xs text-text-muted">{slot.position}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function truncateName(name: string): string {
  return name.length > 8 ? `${name.slice(0, 7)}…` : name;
}

function BestXiSlotList({
  slots,
  selectedBySlotId,
  unfilledBySlotId,
  displayName,
  tb,
  fillTb,
  t,
}: {
  slots: { slotId: string; position: string; line: number; displayOrder: number }[];
  selectedBySlotId: Map<string, BestXiSelectedSlot>;
  unfilledBySlotId: Map<string, BestXiUnfilledSlot>;
  displayName: (c: BestXiCandidate) => string;
  tb: (key: string) => string;
  fillTb: (key: string, vars: Record<string, string>) => string;
  t: <N extends keyof Dictionary>(namespace: N, key: keyof Dictionary[N]) => string;
}) {
  const ordered = [...slots].sort((a, b) => a.displayOrder - b.displayOrder);
  return (
    <div className="rounded-card border border-border bg-surface p-3 sm:p-4">
      <p className="mb-2 text-xs font-semibold text-text-dim">{tb("listViewHeading")}</p>
      <ul className="flex flex-col gap-2">
        {ordered.map((slot) => {
          const sel = selectedBySlotId.get(slot.slotId);
          const unfilled = unfilledBySlotId.get(slot.slotId);
          return (
            <li key={slot.slotId} className="rounded-md border border-border/60 p-2 text-xs">
              {sel ? (
                <details>
                  <summary
                    className="flex cursor-pointer flex-wrap items-center justify-between gap-2"
                    aria-label={fillTb("playerDetailToggleAriaTemplate", { name: displayName(sel.candidate) })}
                  >
                    <span className="flex flex-wrap items-center gap-2">
                      <Badge tone="outline">{slot.position}</Badge>
                      <span className="font-semibold text-text">{displayName(sel.candidate)}</span>
                      {sel.candidate.ruleKind === "legacy" ? <Badge tone="warning">{tb("legacyRuleBadge")}</Badge> : null}
                    </span>
                    <span className="text-2xs text-text-muted">
                      {sel.candidate.buildName ? `${tb("selectedBuildLabel")}: ${sel.candidate.buildName}` : tb("noSavedBuildLabel")}
                    </span>
                  </summary>
                  <div className="mt-2 flex flex-col gap-1.5 border-t border-border/50 pt-2 text-2xs text-text-dim">
                    <p>
                      {tb("suitabilityLabel")}: {t("bestXi", suitabilityLabelKey(sel.suitability.tier))}
                    </p>
                    <p>
                      {tb("positionRatingLabel")}: {sel.positionRating != null ? sel.positionRating : tb("positionRatingUnavailable")}
                    </p>
                    <div>
                      <p className="font-semibold text-text-dim">{tb("reasonsHeading")}</p>
                      <ul className="list-disc pl-4">
                        {sel.reasonCodes.map((code) => (
                          <li key={code}>{t("bestXi", SELECTION_REASON_LABEL_KEY[code] as keyof Dictionary["bestXi"])}</li>
                        ))}
                      </ul>
                    </div>
                    {sel.alternativeCandidateCount > 0 ? (
                      <p>{fillTb("alternativeCandidateCountTemplate", { count: String(sel.alternativeCandidateCount) })}</p>
                    ) : null}
                  </div>
                </details>
              ) : (
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="flex items-center gap-2">
                    <Badge tone="outline">{slot.position}</Badge>
                    <span className="text-text-muted">{tb("slotEmptyLabel")}</span>
                  </span>
                  {unfilled ? (
                    <span className="text-2xs text-warning">{t("bestXi", UNFILLED_SLOT_REASON_LABEL_KEY[unfilled.reason] as keyof Dictionary["bestXi"])}</span>
                  ) : null}
                </div>
              )}
            </li>
          );
        })}
      </ul>
    </div>
  );
}

function BestXiExclusions({
  result,
  displayName,
  tb,
  fillTb,
  t,
}: {
  result: BestXiSelectionResult;
  displayName: (c: BestXiCandidate) => string;
  tb: (key: string) => string;
  fillTb: (key: string, vars: Record<string, string>) => string;
  t: <N extends keyof Dictionary>(namespace: N, key: keyof Dictionary[N]) => string;
}) {
  return (
    <details className="rounded-card border border-border bg-surface p-3 text-xs sm:p-4">
      <summary className="cursor-pointer font-semibold text-text-dim">
        {tb("alternativesHeading")} {result.notableExclusions.length > 0 ? `(${result.notableExclusions.length})` : ""}
      </summary>
      {result.notableExclusions.length === 0 ? (
        <p className="mt-2 text-text-dim">{tb("alternativesEmptyText")}</p>
      ) : (
        <ul className="mt-2 flex flex-col gap-1.5">
          {result.notableExclusions.map((ex) => (
            <li key={ex.candidateKey} className="rounded border border-border/60 p-2">
              <span className="font-semibold text-text-dim">{fillTb("alternativesSlotPrefixTemplate", { position: ex.relatedSlotId.toUpperCase() })}</span>{" "}
              <span className="font-semibold text-text">{displayName(ex.candidate)}</span>
              {ex.candidate.buildName ? <span className="text-text-muted"> ({ex.candidate.buildName})</span> : null}
              <p className="mt-0.5 text-text-dim">{t("bestXi", EXCLUSION_REASON_LABEL_KEY[ex.reasonCode] as keyof Dictionary["bestXi"])}</p>
            </li>
          ))}
        </ul>
      )}
    </details>
  );
}
